#!/bin/bash
function ageask {
echo Nice to meet you, please input your age
read age
}
ageask

function agefiltering {
if [ $age -gt 17 ]
then 
echo "Your age is $age, it's greater than 17. You can watch movie because you are old enough" 
elif [ $age -eq 17 ]
then
echo "Your age is $age, it's equal to 17. You can watch movie because you are old enough" 
elif [ $age -lt 17 ]
then 
echo "Your age is $age, it's less than 17. You are not old enough to watch the movie"
else
echo "Please try again and enter a number" 
ageask
agefiltering
fi
}
agefiltering
