#!/bin/bash
echo I'm practicing if right now! What's your name?
read myname
echo How much salary do you have in mind for this job?
read salary
if [ 49999 -gt salary -lt 75000 ]
	kthen 
	Alright $myname, I accept your request of $annual salary. It"'"s a deal fi
echo We're looking forward to work with you
done
